### ISSUE TITLE
Normalized distance. 

### ISSUE THREAD

**Issue by zilin129** [r-spatial/dtwSat#52]
Hi. I find the dtw distance doesn't consider the normalization using number of alignments. It will cause a problem, more alignments will have larger DTW distance. Can you please provide a option of normalization in the code?

**Comment by vwmaus** [comment]
@zilin129 I don't have this enhancement on my list for the near future but feel free to make a pull request.

**Comment by vwmaus** [comment]
Transfer to `vwmaus/twdtw` <https://github.com/vwmaus/twdtw/issues/5>
