### ISSUE TITLE
no alignments.

### ISSUE THREAD

**Issue by zilin129** [r-spatial/dtwSat#57]
When I'm using the latest version 0.2.8 to calculate the twdtw distance, many timeseries don't have any matched alignments. But if I used the version 0.2.6, most of them can be matched with an alignment. What are the differences of these two versions. I found below is one of the differences. Other differences are in dtw.R. What else? Can you please check which one is correct?
Version 0.2.6
logisticWeight = function(alpha, beta){
  function(psi) 1 / (1 + exp(alpha * (psi - beta )))
}
cm = phi * weight.fun(psi)

Version 0.2.8
logisticWeight = function(alpha, beta){
  function(phi, psi) phi + 1 / (1 + exp(alpha * (psi - beta )))
}
cm = weight.fun(phi, psi)

**Comment by vwmaus** [comment]
There has been an error in version 0.2.6 that has been fixed in the newer version. I suggest installing a new version `>1.0-0`, which allows users to define their own weighting function, for details see `?twdtw`.
