### ISSUE TITLE
extraction of  bands from ".hdf" format and those series of bands to be stack in single image on R-program

### ISSUE THREAD

**Issue by hemubinni** [r-spatial/dtwSat#58]
Dear Sir,

I am Hemanth, a Remote Sensing expert working on a project related to Land Use and Land Cover (LULC) for crop analysis in drought-prone areas. I am currently facing an issue in extracting bands from MOD13Q1 dataset, which are in ".hdf" format, and stacking them into a single image using the code. I am seeking your valuable suggestions on any alternative processes for performing these tasks in R program.

Thank you in advance for your time and assistance.

**Comment by vwmaus** [comment]
The new package version should handle MODIS hdf files using `stars`. Please reinstall it with `install.packages("dtwSat")`. Please see this for the new workflow <https://r-spatial.github.io/dtwSat/articles/landuse-mapping.html> and this to read hdf as stars <https://rpubs.com/michaeldorman/723959>.
