### ISSUE TITLE
Error in `split.stars(x, c("time"))`: length(x) == 1 is not TRUE

### ISSUE THREAD

**Issue by vwmaus** [r-spatial/dtwSat#62]
Error in Flavors [r-oldrel-macos-arm64](https://cran.r-project.org/web/checks/check_flavors.html#r-oldrel-macos-arm64) and [r-oldrel-macos-x86_64](https://cran.r-project.org/web/checks/check_flavors.html#r-oldrel-macos-x86_64).

Details in <https://cran.r-project.org/web/checks/check_results_dtwSat.html>

**Comment by vwmaus** [comment]
@edzer, CRAN results show the following error on the r-oldrel-macos-arm64 and r-oldrel-macos-x86_64 flavors.
Could you point me in the right direction for addressing this? Or is it an issue that needs to be resolved within stars itself?

```
     Error in `split.stars(x, c("time"))`: length(x) == 1 is not TRUE
     Backtrace:
     ▆
     1. ├─base::system.time(...) at test-twdtw_classify.R:24:0
     2. └─dtwSat::twdtw_knn1(...)
     3. ├─base::split(x, c("time"))
     4. └─stars:::split.stars(x, c("time"))
     5. └─base::stopifnot(length(x) == 1)
```

**Comment by edzer** [comment]
Thanks! Those two platforms have a broken GDAL install (no netcdf linked to GDAL), so stars tests break on them, and old stars versions are kept/used. This will go away when a new release of R appears, and "oldrel" moves up to current release - no need to take action.

**Comment by vwmaus** [comment]
Thanks!
