### ISSUE TITLE
processing in parallel

### ISSUE THREAD

**Issue by saeedha93** [r-spatial/dtwSat#67]
Hello with respect
How can I do the processing in parallel in version 1.0?
thanks so much

**Comment by vwmaus** [comment]
@saeedha93, from `dtwSat` 1.0 `stars` is used for data handling.
You could look at how to do parallel processing with stars here <https://r-spatial.org/r/2023/09/21/stars-parallel.html>.

**Comment by saeedha93** [comment]
Thank you very much
And thank you for your reply
Another question is that when we create a time series, if we use the cloud
mask image from the same scene, the code gives an error
When I delete the masked images, it runs perfectly.
Is it possible to make it work with masked images?
best
